# Generated by Django 4.2.7 on 2024-08-12 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('balanceit', '0003_dataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_column', models.CharField(max_length=100)),
                ('sampler', models.CharField(max_length=100)),
                ('sampler_parameters', models.JSONField(default=dict)),
                ('model', models.CharField(max_length=100)),
                ('model_parameters', models.JSONField(default=dict)),
                ('accuracy', models.FloatField()),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('f1_score', models.FloatField()),
                ('roc_auc', models.FloatField()),
                ('gmean', models.FloatField()),
                ('mcc', models.FloatField()),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='balanceit.dataset')),
            ],
        ),
    ]
